whi_ur_robot_driver_bridge:
  ros__parameters:
    payload_weight: 4.5 # unit Kg
    payload_to_tcp: [0.0, -0.17, 0.08]
    try_duration: 10.0 # second
    try_max_count: 20
    external_program: external_ctrl.urp
    protective_query_frequency: 20.0 # Hz
    ur_driver_patience: 55.0 # second
    moveit_cpp_state_topic: moveit_cpp_state
    debug:
      print_standby_state: false
